### ISSUE TITLE
Nested label creation from sidebar contextual menu creates label at the top level

### ISSUE THREAD

**Issue by rfbarraza** [mimestream/new-bugs#71] opened 2020-12-23 17:18 UTC
**Description**
Right click on an item in the sidebar and select "New Label" from the contextual menu. A new top level label is created.

**Reproducibility**
Always

**To Reproduce**
1. Select label in sidebar
2. Open contextual menu for said item
3. Select “New Label"
4. New Label is crearted at the top level

**Expected Behavior**
New Label to be nested under the label clicked. You’ve the hierarchy available from the item -and- you’re able to create nested labels via / delimited strings so it feels like this -might- be some delicious low hanging fruit (even if better support for nested labels is listed as under the Planned section of the Mimestream roadmap)

**Screenshots**
https://user-images.githubusercontent.com/24500089/103021785-fa381880-4507-11eb-94f8-96f6e4f1db60.mov

**Configuration**
- OS: 10.15.7 (19H114)
- Mimestream: 0.8.3 (114)

**Comment by neiljhaveri** [comment] 2020-12-31 02:30
100% agree, thanks!

**Comment by neiljhaveri** [comment] 2020-12-31 04:08
Ah, there's an earlier report with the same complaint. Duplicate of #44.

**Closed** 2020-12-31 04:24 UTC
Labels: bug, import, in:sidebar, reviewed
