### ISSUE TITLE
Swipe actions are difficult to use because of frequent list refreshes

### ISSUE THREAD

**Issue by michaellenaghan** [mimestream/new-bugs#9] opened 2020-10-07 14:08 UTC
**Describe the bug**
Let's say I have many emails in my inbox. I swipe to delete one, and then start swiping to delete another. The swipe is aborted mid-effort because the list refreshes.

This makes it difficult to quickly process a bunch of new emails one by one.

**To Reproduce**
1. Say you have at least three emails in your inbox.
2. Delete or archive one by swiping.
3. Delete or archive another by swiping.
4. Delete or archive another by swiping.
5. Previous deletes/archives often cause list refreshes that abort subsequent deletes/archives mid-swipe.

**Expected behavior**
The current behaviour makes swipe-to-delete/archive frustrating, and almost unusable. If the problem can't be fixed for technical reasons, maybe swiping shouldn't be an option? (Having said that, it would still be useful to have *some* way to quickly process emails using the trackpad.)

**Screenshots**
This would need a movie rather than a screenshot. I could perhaps do that, but I'd need to set up some sample data, etc.

**Configuration:**
 - macOS Catalina 10.15.7
 - Mimestream 0.6.26

**Comment by anrope** [comment] 2020-10-07 19:10
+1

I've been fighting this too, here's a video:

https://streamable.com/9q2pik

I'm doing a short swipe then click, trying to archive a bunch of consecutive emails.

This works fine in the default Mail app, so hopefully it's a quick-but-subtle fix.

Thanks for making Mimestream!

**Comment by neiljhaveri** [comment] 2020-10-10 19:10
Thanks for reporting this! I can easily reproduce this, and I agree this is super super annoying.

Unfortunately, I don't see any way to fix this without a major overhaul of the data structure behind the message list. It's a sparse data structure, which seemed "right" at first, but is now the root cause of so many hard-to-fix issues, including this one. I'm going to give up on the sparse data structure – a quick test shows a non-sparse approach for 1 million conversations only costs ~15MB in RAM.

I'm currently knocking out the Big Sur UI refresh, but this overhaul is on the list next (as is the Message list filter feature).

**Comment by michaellenaghan** [comment] 2020-10-12 14:18
Mmmm I don't know anything about your code, of course, but I'm not sure how the data structure explains this? It just seems like the entire list is being refreshed, `reloadData()`-style, instead of rows being selectively added and removed from the list. At least, that's what it looks like from the outside.

Just thinking out loud.

**Comment by neiljhaveri** [comment] 2020-10-12 15:22
Correct, the entire list is being refreshed via reloadData(). A sparse structure makes it tricky to compute add/remove/move row modifications, because you run into situations where an individual message is updated, it's not currently in the list scope, but it potentially used to be part of a conversation that is in the list scope, but this conversation is outside of the loaded range. For example: you have range 0-200 loaded, but this selective message update effectively causes the scoped date of an existing conversation to move from index 1000 to index 2000. It's tricky to figure this out, so then current code just does a full reload. With at least a single ID in memory for each conversation, handling these kinds of updates becomes a lot easier – hopefully I will just be able to fully move to SwiftUI List.

**Comment by michaellenaghan** [comment] 2020-10-12 21:29
Truly, feel free to ignore this; just curious, and no doubt you're a little busy. :-) Still, sometimes it helps to talk out loud.

I don't fully understand your example, but: regardless of the underlying data structure, you ultimately generate a nested array of rows within sections. (Based on your last comment I'm assuming you're using UIKit right now, but I may have misunderstood.) If you hang on to your old rows within sections you can use  [`difference(from:)`](https://developer.apple.com/documentation/foundation/data/3200261-difference) + [`inferringMoves()`](https://developer.apple.com/documentation/swift/collectiondifference/3200819-inferringmoves) to calculate the deltas for you, as long as the elements are hashable. No? (If it's of interest I can explain how I use those routines myself to calculate deltas. It's certainly not difficult, but it's not  instantly obvious either.)

**Comment by neiljhaveri** [comment] 2020-10-15 21:34
So, I think we're saying the same thing – I've been trying to switch over to CollectionDifference, and am about halfway there. What I meant by the current structure being "sparse" is that even for a list of 10,000 scrollable conversations, the insert/move/remove/update operations were being inferred without ever requiring a full backing array in memory (e.g. only ~200 objects in memory). This is where the challenges came into play, and why some cases fell back to a NSTableView.reloadData().

**Comment by neiljhaveri** [comment] 2020-10-17 04:50
I have this fix committed and it will be in the next update.

**Closed by neiljhaveri** 2020-10-17 04:50 UTC
Labels: bug, screened
