### ISSUE TITLE
Reply includes only partial quoted text sometimes

### ISSUE THREAD

**Issue by albireox** [mimestream/new-bugs#46] opened 2020-10-22 18:00 UTC
**Describe the bug**

When replying to an email in a thread, sometimes the quoted text is incorrect. This seems to happen especially with mailing lists that at the bottom include a "letterhead" like

```
_______________________________________________
The LVM Instrument Mailing List <lvm-XXX@XXX.org>
https://mailman.xxxx.org/mailman/listinfo/lvm-XXXX
```

for each message. In some cases (not always), when you click reply the only quoted text is the letterhead, and the rest of the message is not included as a quote.

**To Reproduce**
I don't know exactly when this is triggered; in most cases a message from a mailing list is quoted correctly. I can provide screenshots if that helps.

**Expected behavior**
The full email text is quoted in the reply.

**Configuration:**
 - OS: macOS Big Sur b10
 - Mimestream Version v0.7.1b

**Comment by neiljhaveri** [comment] 2020-11-19 09:31
Sorry about the delay in responding.

Would you be willing to share the raw source of this message with me, so I can debug? If you’d prefer not to – I totally and completely understand, and I’ll keep an eye on this issue. But if you are able, click the (…) menu in the message’s header, click View Raw Source, and from that new window select File > Save to save it as a .eml file that you can either attach, or email to support@mimestream.com

**Comment by albireox** [comment] 2020-11-19 18:41
I sent you an email with a message that has the same problem.

**Comment by neiljhaveri** [comment] 2020-11-20 09:04
Thank you. I checked your email and this is a duplicate of mimestream/mimestream#103 (a private repository issue). We'll try to fix this soon!

**Closed by neiljhaveri** 2020-11-20 09:04 UTC
Labels: bug, question
