### ISSUE TITLE
Replying to an email loads images

### ISSUE THREAD

**Issue by lightbody** [mimestream/new-bugs#43] opened 2020-10-19 15:05 UTC
**Describe the bug**
I hadn't clicked the "load images" button in an email I was replying to, but I noticed that when I replied I could see the image loaded in the response I was drafting up. I think you have a bug that pulls down images on reply, even if the user hasn't yet clicked the button to allow it.

**To Reproduce**
1. Receive an email with an embedded email. Notice it doesn't display.
2. Reply to the email.
3. See the image displayed in the quoted email in your reply.

**Expected behavior**
No image displayed :)

**Configuration:**
 - OS: 11.0 Beta (20A5395g)
 - Mimestream Version 0.7.0c (101)

**Comment by neiljhaveri** [comment] 2020-12-31 04:25
This is definitely a bug, thanks for reporting it!

**Comment by neiljhaveri** [comment] 2020-12-31 04:34
Already tracking internally as Duplicate of mimestream/mimestream#590, planning to fix soon! Thanks again :)

**Closed** 2020-12-31 04:34 UTC
Labels: bug, duplicate, in:compose, reviewed
