### ISSUE TITLE
Mimestream is not using "Signature defaults" from my gmail settings

### ISSUE THREAD

**Issue by nratter** [mimestream/new-bugs#99] opened 2021-08-03 18:26 UTC
**Describe the bug**
Mimestream is not using "Signature defaults" from my gmail settings.

**To Reproduce**
1. Create 2 signatures in your gmail settings (let's call them SignatureA and SignatureB)
2. Under "Signature defaults", set "For new emails use" to SignatureA and "on reply/forward use" to SignatureB.
3. In Mimestream, reply to an email that you receive.

**Expected behavior**
You would expect when replying to emails that SignatureB would be used as you defined in your settings, but SignatureA is used instead.

**Configuration:**
 - OS: macOS Catalina
 - Mimestream Version: 0.26.2

**Comment by neiljhaveri** [comment] 2021-08-03 18:34
Thank you for the feedback! 

Unfortunately, the Gmail API does not support the multiple and reply-only signatures feature in Gmail. To help express support for this API functionality, please star this issue: https://issuetracker.google.com/issues/157581366

Since we can't sync this and automatically do the right thing, we plan to add support for client-side signature configuration; this is being tracked as a feature at https://portal.productboard.com/mimestream/1-mimestream-roadmap/c/45-support-multiple-and-reply-only-signatures.

Please add a +1 there to get notified when support is added! We're closing this issue instead as we're tracking this as a feature, not a bug.

**Closed by neiljhaveri** 2021-08-03 18:34 UTC
Labels: bug
