### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by joconcepts** [mimestream/new-bugs#61] opened 2020-12-03 10:59 UTC
**Describe the bug**
High CPU usage, even when in background

**To Reproduce**
It occurs from time to time, no pattern recognized. After running some minutes, clicking around, it occurs. No obvious reason.

**Expected behavior**
Low CPU usage.

**Screenshots**
<img width="1072" alt="Bildschirmfoto 2020-12-03 um 11 57 37" src="https://user-images.githubusercontent.com/778836/101000957-d6179600-355e-11eb-8c55-1fc1e2a67599.png">

**Configuration:**
Mimestream: Version 0.7.7
macOS: Version 11.1 (Build 20C5048k)

**Comment by neiljhaveri** [comment] 2020-12-06 03:51
Can you select Mimestream, click the (...) button in the toolbar, click sample, and attach a copy of the sample? Thanks!

**Comment by joconcepts** [comment] 2020-12-07 10:00
Attached the requested file (hope that it is the correct one)
[sample_mimestream.txt](https://github.com/mimestream/new-bugs/files/5651914/sample_mimestream.txt)

**Comment by marrrc** [comment] 2020-12-10 10:01
I am having the same issue & I suspect it could be related to Big Sur since this started yesterday after I upgraded from Catalina.

**Comment by neiljhaveri** [comment] 2020-12-10 15:58
Yeah, I've gotten a few emails about this now, and I think this is only happening on Big Sur. I got this to happen a few times on my MacBook Pro, but haven't seen it happen when connected to an external 4K monitor. Unfortunately, I couldn't figure it out while I had reproducing it in the debugger, and then it magically stopped happening. One pattern I noticed was that it seemed to happen when there were few messages in the list, and it stopped as soon as I selected a mailbox with a lot of different messages.

Either way, sounds like a lot of people are seeing this on Big Sur – I'll try and investigate soon.

**Comment by neiljhaveri** [comment] 2020-12-10 16:11
Duplicate of mimestream/mimestream#1281

**Comment by joconcepts** [comment] 2020-12-22 17:05
any. update on this?

**Comment by neiljhaveri** [comment] 2020-12-23 16:59
None, unfortunately. I haven't been able to get it to happen again since I saw it the first few times, after upgrading to 11.1. 
- Are you still seeing this on 11.1? 
- What Mac are you using? 
- Are you using the built-in display, or external monitor (and if so what resolution is it)? 

If anybody has clues on how to reproduce this, comments would be greatly appreciated

**Comment by joconcepts** [comment] 2020-12-23 17:24
Strange. I've completely removed the app using AppCleaner and installed it again. I can still reproduce it, but only when using the internal display. When using an external display it does not occur.

I'm on Macos 11.1 and using a Macbook Pro 13 2018.

**Comment by joconcepts** [comment] 2020-12-23 17:25
But not always... strange thing.

**Comment by neiljhaveri** [comment] 2020-12-23 17:33
Thanks for the extra info. Yeah, that's what I saw on my 15" 2018 Pro too… only happening with the internal display, never with an external. I've since switched to a 13" M1-based Air and just can't get this to happen at all – in retrospect maybe I shouldn't have gotten rid of my Intel-based Mac so quickly, oops.

Does it tend to reproduce more when the message list has a "bar" across the top, or not? e.g. in Search, or in Promotions/Updates? Have you seen this occur with a list that doesn't have a bar across the top?

Thanks for helping narrow this down... The backtrace for this CPU usage is entirely in AppKit and other system frameworks, without any real indication of what's actually causing the issue, so it's tough to even speculate on the root cause.  It does seem like a bug in an Apple framework to me, since it only started happening on Big Sur and the same code seems to run fine on Catalina, but I'll need to figure out a reproducible case to (a) report it to Apple, and (b) see if there's some way to work around it.

**Comment by joconcepts** [comment] 2020-12-27 16:44
So in my testing it always happens when changing between different message lists like primary or promotions. When opening a fresh instance of mimestream the load keeps down. When changing the message list the first time the cpu usage gets up.

**Comment by neiljhaveri** [comment] 2020-12-28 18:02
A few more follow-up questions:
- Does resizing the width of the message list have any impact?
- Does resizing the window size have any impact? 
- Does this only occur in message lists that have a bar across the top, like Promotions? Or does it occur in Primary too? 
- Does holding command and clicking on the currently-selected sidebar item to de-select it, and having an empty list, still leave the CPU usage high?

I did have somebody else email me about this, and that they are encountering it on an M1 Mac, so I'm hopeful that I can get some tips on how to reproduce it from them. I'd really, really like to figure out how to get this to reproduce on my system in the debugger so I can get to the bottom of it.

**Comment by neiljhaveri** [comment] 2020-12-30 20:19
So... in the last 24h, I ran into this twice on my M1 MacBook Air. Today, I ran into it in Notes as well – same exact stack, and it seems to be a somewhat common problem: https://forums.macrumors.com/threads/apple-notes-using-cpu.2268511/

I'm trying to figure out how to reproduce this on demand, so that I can (A) put together good bug report for Apple, and (B) try some possible workarounds.

**Comment by neiljhaveri** [comment] 2020-12-30 23:05
I finally found a way to reproduce this. It seems to be a bug in AppKit, and I can reproduce this in Notes too. I did come up with what is hopefully a way to avoid it until Apple fixes this issue. Here is a version with the fix:
https://storage.googleapis.com/mimestream-releases/Mimestream_0.8.4a.dmg

If this fixes the problem for you, please report back!

**Comment by neiljhaveri** [comment] 2020-12-30 23:10
Pushing this bug fix and closing the issue; please reopen or email support@mimestream.com if this issue reoccurs on v0.8.5 once released (or the intermediate v0.8.4a linked above).

**Closed by neiljhaveri** 2020-12-30 23:10 UTC
Labels: bug, duplicate, reviewed
